### ISSUE TITLE
rotationVelocity returns incorrect value around half-rotation

### ISSUE THREAD

**Issue by mmurooka** [jrl-umi3218/SpaceVecAlg#42]
`rotationVelocity` returns incorrect value around half-rotation.
By executing the following code, you get output
```
sva::RotZ(M_PI): 3.14159
sva::RotZ(M_PI - 1e-10): 2.56531e+06
```
The value in the second line is obviously incorrect.

Plotting `testRotationVelocityResult.txt` dumped by executing the code gives the following graph, which shows that `Eigen::AngleAxis` returns the correct value even around half-rotation, and that there is no problem in the rotation matrix generation by `sva::RotZ`.
![testRotationVelocityResult](https://user-images.githubusercontent.com/6636600/157383993-0c29d2ab-bb0e-4f12-a93f-05fa7bc8b9f5.png)

### Code to reproduce
```c++
// g++ `pkg-config --cflags eigen3` `pkg-config SpaceVecAlg --cflags` `pkg-config SpaceVecAlg --libs` testRotationVelocity.cpp -o testRotationVelocity

#include <iostream>
#include <iomanip>
#include <fstream>
#include <SpaceVecAlg/SpaceVecAlg>

int main()
{
  std::ofstream ofs("/tmp/testRotationVelocityResult.txt");

  std::cout << "sva::RotZ(M_PI): " << sva::rotationVelocity(sva::RotZ(M_PI)).z() << std::endl;
  std::cout << "sva::RotZ(M_PI - 1e-10): " << sva::rotationVelocity(sva::RotZ(M_PI - 1e-10)).z() << std::endl;

  for(double angle = -1e-7; angle < 1e-7; angle += 1e-9)
  {
    ofs << std::setprecision(10)
        << angle + M_PI << " "
        // Make rotatin matrix by sva::RotZ and convert to Yaw angle by sva::rotationVelocity
        << sva::rotationVelocity(sva::RotZ(angle + M_PI)).z() <<  " "
        // Make rotatin matrix by sva::RotZ and convert to Yaw angle by Eigen::AngleAxisd
        << Eigen::AngleAxisd(sva::RotZ(angle + M_PI).transpose()).angle() <<  " "
        // Make rotatin matrix by Eigen::AngleAxisd and convert to Yaw angle by sva::rotationVelocity
        << sva::rotationVelocity(Eigen::AngleAxisd(angle + M_PI, Eigen::Vector3d::UnitZ()).inverse().toRotationMatrix()).z() << std::endl;
  }
}
```

**Comment by gergondet** [comment]
Hi @mmurooka 

Thanks for bringing this up. I think the problem is that `sinc_inv` (used [here](https://github.com/jrl-umi3218/SpaceVecAlg/blob/master/src/SpaceVecAlg/PTransform.h#L301)) is not defined when `sin(theta) == 0` (expect when theta is 0) and it degenerates when we get close to those values.

The following patch keeps the value in check but there's a sign flip when the angle is more than `M_PI` (something similar happens around `-M_PI` which I'm not sure we can work-around?

```diff
diff --git a/src/SpaceVecAlg/PTransform.h b/src/SpaceVecAlg/PTransform.h
index 51a804a..50ca65d 100644
--- a/src/SpaceVecAlg/PTransform.h
+++ b/src/SpaceVecAlg/PTransform.h
@@ -297,9 +297,16 @@ inline Eigen::Vector3<T> rotationVelocity(const Eigen::Matrix3<T> & E_a_b)
   T acosV = (E_a_b(0, 0) + E_a_b(1, 1) + E_a_b(2, 2) - 1.) * 0.5;
   T theta = std::acos(std::min(std::max(acosV, -1.), 1.));
 
-  w = Eigen::Vector3<T>(-E_a_b(2, 1) + E_a_b(1, 2), -E_a_b(0, 2) + E_a_b(2, 0), -E_a_b(1, 0) + E_a_b(0, 1));
-  w *= sinc_inv(theta) * 0.5;
 
+  w = Eigen::Vector3<T>(-E_a_b(2, 1) + E_a_b(1, 2), -E_a_b(0, 2) + E_a_b(2, 0), -E_a_b(1, 0) + E_a_b(0, 1));
+  if(std::fabs(theta) > 3 && std::fabs(std::sin(theta)) < 1e-7)
+  {
+    w = theta * w.normalized();
+  }
+  else
+  {
+    w *= sinc_inv(theta) * 0.5;
+  }
   return w;
 }
```

Bringing in @aescande into the conversation as he's worked around this code in the past and is definitely has more expertise than me on those numerical issues.

**Comment by aescande** [comment]
I will have a better look at this later, to see how to deal with the quasi infinite values (maybe [this](https://vision.in.tum.de/_media/members/demmeln/nurlanov2021so3log.pdf)  could help). 
But as a side comment `rotationVelocity` is simply a `log` on `SO(3)`, which is a multi-valued function. The discontinuity at the half angle is due to the choice of branch we make. It is unavoidable to have to make this choice somewhere, and since we usually deal with small angles, it makes sense to have it at `pi`.

**Comment by mmurooka** [comment]
@gergondet and @aescande 

Thank you for the comments.

The use-case where I found this issue is really simple: extracting roll-pitch-yaw from rotation matrix in **Python**.
https://github.com/mmurooka/Motion6DoF/blob/34fa4c196d55e381b26e814769ba0a4317b65ac1/etc/scripts/DumpBipedCommands.py#L50-L53

Now I'm using [ROS TF utilities](http://docs.ros.org/en/jade/api/tf/html/python/transformations.html). Maybe `aa = e.AngleAxisd(pose.rotation().transpose()); aa.angle * aa.axis` is another possible way, I didn't use it just because I'd forgotten it.
In C++, the easiest way to get roll-pitch-yaw is using [mc_rbdyn::rpyFromMat](https://github.com/jrl-umi3218/mc_rtc/blob/4609530431e5177e503ae7ea7d5d011d0dd06ebe/include/mc_rbdyn/rpy_utils.h#L83), so it whould be useful if this is binded to Python.

**Comment by aescande** [comment]
What do you want to have in the end? Any 3-parameters representation of a rotation or a specific one?
Because `log` or `AngleAxis` are not the same as roll-pitch-yaw. 
Be careful also that all 3d representations exhibit singularities that'll be harmful for most (any?) applications where smoothness is important.

**Comment by mmurooka** [comment]
The use-case this time is to output yaml format string that describes the contact poses for loading with mc_rtc.
mc_rtc uses `mc_rbdyn::rpyToMat` [to convert 3-dimensional array to rotation matrix](https://github.com/jrl-umi3218/mc_rtc/blob/4609530431e5177e503ae7ea7d5d011d0dd06ebe/src/mc_rtc/Configuration.cpp#L415
), so roll-pitch-yaw should be described in yaml format string. So the answer of
> What do you want to have in the end? 

is using `mc_rbdyn::rpyFromMat` in Python. (If I understand correctly, this binding is not implemented yet)

And independent of what is needed for my use-case, I think the incorrect returning value (the value of order of `1e6`) of `rotationVelocity` for half-rotation described in this Issue could cause unexpected problems elsewhere, so I think it would be a good thing to improve it (although it may not be a high priority).

**Comment by aescande** [comment]
> And independent of what is needed for my use-case, I think the incorrect returning value (the value of order of 1e6) of rotationVelocity for half-rotation described in this Issue could cause unexpected problems elsewhere, so I think it would be a good thing to improve it (although it may not be a high priority).

This is definitely something to handle/correct. There might be also similar care to take with the derivatives of `log`. I'll try to have a look at it next week.

**Comment by gergondet** [comment]
@mmurooka 

> The use-case this time is to output yaml format string that describes the contact poses for loading with mc_rtc.

This is unrelated to the issue but mc_rtc acccepts rotation matrix, quaternion and rpy representations when loading a pose, so instead of:
```python
rotation: [{4[0]}, {4[1]}, {4[2]}]""".format(
#...
  tf.transformations.euler_from_matrix(np.array(footPose.rotation().transpose()))
```
you can use:
```python
rotation: [{4[3], 4[0]}, {4[1]}, {4[2]}]""".format(
#...
# Note coeffs returns [x, y, z, w] but mc_rtc expects w, x, y, z
  eigen.Quaterniond(footPose.rotation().transpose()).coeffs()
```

> is using mc_rbdyn::rpyFromMat in Python. (If I understand correctly, this binding is not implemented yet)

Will add that :)

@aescande

> This is definitely something to handle/correct. There might be also similar care to take with the derivatives of log. I'll try to have a look at it next week.

Will you implement (10) from [the paper you linked](https://vision.in.tum.de/_media/members/demmeln/nurlanov2021so3log.pdf)?

**Comment by aescande** [comment]
> Will you implement (10) from [the paper you linked](https://vision.in.tum.de/_media/members/demmeln/nurlanov2021so3log.pdf)?

The ideas of sections 2.2 seems more workable than (10), but there are still some question marks around the special case of a rotation of almost `pi` around a (almost) unit axis.
I did some quick tests in Matlab but I will need to dig further and then go to C++. I'll have more time for that next week.
